# Usa uma imagem leve do Alpine Linux
FROM alpine:latest

# Define autor (opcional)
LABEL maintainer="seu-nome@exemplo.com"

# Comando básico para o build mostrar algo
RUN echo "Build realizado com sucesso no Alpine!"

# Comando padrão ao iniciar o container
CMD ["echo", "Container rodando com sucesso!"]
###
